- name: Salesforce Deploy Action
  # You may pin to the exact commit or the version.
  # uses: gfarb/sfdx-deploy@f6af3edd68955f50306d8d26290224e0f57f78c8
  uses: gfarb/sfdx-deploy@v1
  with:
    # Username or alias for the target org. Must be pre-authorized.
    TARGET_USERNAME: 
    # Comma-separated list of paths to the local source files to include in the manifest.
    SOURCE_PATH: # optional
    # Path to folder containing manifests (destructiveChangesPre.xml, destructiveChangesPost.xml) of components to delete before and/or after the deploy.
    DESTRUCTIVE_CHANGES: # optional
    # Level of deployment tests to run. The default value is RunLocalTests.
    TEST_LEVEL: # optional
    # Number of minutes to wait for the command to complete. The default value is 33 minutes.
    WAIT: # optional
